<a href="https://colab.research.google.com/github/pschwartz222/MA-576/blob/main/PositiveDefinite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import eig
from numpy import linalg as LA
import math
import random

In [ ]:
A = np.array([[1, 2], [2, 1]])
u, T = eig(A) #outputs and array with the eigenvalues of A and a matrix whose columns are the eigenvectors of A

print(A, '\n')
print(u, '\n')
print(T, '\n')

v = T[:,0:1]

print(A @ v, '\n') #check that v is an eigenvector of A
print(3*v, '\n')

D = LA.inv(T) @ A @ T #Diagonalize

print(D, '\n')

print(T @ D @ LA.inv(T))

[[1 2]
 [2 1]] 

[ 3. -1.] 

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 

[[2.12132034]
 [2.12132034]] 

[[2.12132034]
 [2.12132034]] 

[[ 3.00000000e+00  4.44089210e-16]
 [ 6.66133815e-16 -1.00000000e+00]] 

[[1. 2.]
 [2. 1.]]


In [ ]:
def makeMatrix(n): #outputs an (n x n) invertible, symmetric matrix
  L = np.random.rand(n,n)
  while np.linalg.det(L) == 0:
    L = np.random.rand(n,n)
  A = L @ L.T
  return(A)


In [ ]:
A = makeMatrix(4)
print(A)

[[1.66158535 1.32021088 1.77849773 0.60114786]
 [1.32021088 1.69260931 1.36337961 0.65648344]
 [1.77849773 1.36337961 2.26277223 0.63183248]
 [0.60114786 0.65648344 0.63183248 0.59840811]]


In [ ]:
def Sylvester(A): #input a square symmetric matrix with positive entries on the main diagonal.
  signs = []
  n= len(A)
  for i in range(1,n+1):
   block = A[:i, :i]
   d = LA.det(block)
   signs.append(d > 0)
  if all(signs) == True:
    print('Positive definite')
  else:
    print('Not positive definite')

In [ ]:
Sylvester(A)

Positive definite


In [ ]:
for i in range(10):
  A = makeMatrix(4)
  Sylvester(A)

Positive definite
Positive definite
Positive definite
Positive definite
Positive definite
Positive definite
Positive definite
Positive definite
Positive definite
Positive definite


In [ ]:
print(A)

[[2.0853787  1.59422591 1.86835069 1.12156657]
 [1.59422591 2.1443549  1.57868729 0.86863622]
 [1.86835069 1.57868729 1.89281681 0.99790215]
 [1.12156657 0.86863622 0.99790215 0.65058043]]


In [ ]:
def diagonalize(A): #input a diagonalizable matrix
  n = len(A)
  u, P = eig(A)
  D = np.diag(u)
  return D, P

In [ ]:
D, P = diagonalize(A)

In [ ]:
print(LA.inv(P)@ A @ P, "\n")
print(P @ D @ LA.inv(P))

[[ 5.96611765e+00 -1.11022302e-16 -2.22044605e-16 -5.55111512e-16]
 [ 3.26128013e-15  6.35604221e-01  2.08166817e-16 -2.01227923e-16]
 [-2.58126853e-15 -2.55871713e-16  3.36654447e-02  1.68268177e-16]
 [ 2.98372438e-15  3.53883589e-16 -6.24500451e-17  1.37743532e-01]] 

[[2.0853787  1.59422591 1.86835069 1.12156657]
 [1.59422591 2.1443549  1.57868729 0.86863622]
 [1.86835069 1.57868729 1.89281681 0.99790215]
 [1.12156657 0.86863622 0.99790215 0.65058043]]


In [ ]:
B = np.array([[1,2], [2,1]])

D, P = diagonalize(B)

print(LA.det(B))

print(LA.inv(P) @ B @ P)

-2.9999999999999996
[[ 3.00000000e+00  4.44089210e-16]
 [ 6.66133815e-16 -1.00000000e+00]]


In [ ]:
A = makeMatrix(4)
delta, T = diagonalize(A)
B = LA.inv(T) @ A @ T
C = B.round(9)
print(C)

[[ 4.42302731e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.92797000e-03 -0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -0.00000000e+00  7.12730517e-01 -0.00000000e+00]
 [ 0.00000000e+00 -0.00000000e+00 -0.00000000e+00  4.54871481e-01]]
