<a href="https://colab.research.google.com/github/pschwartz222/MA-576/blob/main/Simplex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import eig
from numpy import linalg as LA
import matplotlib.pyplot as plt
import itertools

In [ ]:
A = np.array([[2, 3, -1, -1], [4, 1, 1, -2]])
m = len(A)
n = len(A[0])
index = list(range(n))
print('m =', m, 'n =', n)
print(index)

m = 2 n = 4
[0, 1, 2, 3]


In [ ]:
print(A)

[[ 2  3 -1 -1]
 [ 4  1  1 -2]]


In [ ]:
C = A[:,[0,2]]
print(C)

[[ 2 -1]
 [ 4  1]]


find all subsets of {0,1,2,...,n-1} of cardinality m.

In [ ]:
for subset in itertools.combinations(index, m):
  print(subset)

(0, 1)
(0, 2)
(0, 3)
(1, 2)
(1, 3)
(2, 3)


pick out the matrix whose columns are indexed by subset

In [ ]:
C = A[:, subset]
print(C)

[[-1 -1]
 [ 1 -2]]


In [ ]:
def basic_solution(A, b): #A is an (m x n) matrix of rank m (n>m) and b is a column with m entries
  m = len(A)
  n = len(A[0])
  index = list(range(n))
  numb_comb = 0 #we will count the number of combinations of m columns that are linearly independent
  for subset in itertools.combinations(index,m):
    A_B = A[:,subset]
    if np.linalg.det(A_B) != 0:
      numb_comb = numb_comb+1

  X = np.zeros((n,numb_comb))
  comb=0
  for subset in itertools.combinations(index, m):
   A_B = A[:, subset]
   if (np.linalg.det(A_B) != 0):
    x_B = LA.inv(A_B) @ b
    x = np.zeros((n,1))
    for k in range(m):
      i = subset[k]
      x[i,0] = x_B[k,0]
      X[i, comb] = x_B[k,0]
    comb=comb+1
    #print(x)
  print('number of basic solutions:', numb_comb)
  return(X) #each column is a basic solution

In [ ]:
b = np.array([[-1], [9]])
print(b)

[[-1]
 [ 9]]


Find the basic solutions of Ax=b where A is an m x n matrix of rank m.

In [ ]:
M=basic_solution(A,b)
print(M)

number of basic solutions: 5
[[ 2.8         1.33333333  0.          0.          0.        ]
 [-2.2         0.          2.         -2.2         0.        ]
 [ 0.          3.66666667  7.          0.          3.66666667]
 [ 0.          0.          0.         -5.6        -2.66666667]]


Perform Simplex method

In [ ]:
b_1 = np.matrix([[12], [4]])
Q = np.array([[2, 4, 1, 0], [1, 1, 0, 1]])
print(Q)

[[2 4 1 0]
 [1 1 0 1]]


In [ ]:
m_1 = len(Q)
print(m_1)
n_1 = len(Q[0])
print(n_1)

2
4


In [ ]:
N = basic_solution(Q,b_1)

number of basic solutions: 6


In [ ]:
print(N)

[[ 2.  4.  6.  0.  0.  0.]
 [ 2.  0.  0.  4.  3.  0.]
 [ 0.  4.  0. -4.  0. 12.]
 [ 0.  0. -2.  0.  1.  4.]]


In [ ]:
f = np.array([2, 3, 0, 0])

given a matrix M whose columns are basic solutions, we reduce to the basic feasible solutions and find the maxiumum output.

In [ ]:
def find_maximum(M, c):
  n = len(M[0])
  positive_cols = []
  values = []
  for i in range(n):
    if all(M[:,i] >= 0) :
      positive_cols.append(i)
      values.append(c.T @ M[:,i])
  N = M[:, positive_cols]
  max_value = max(values)
  return N, max_value

In [ ]:
T, max_value = find_maximum(N,f)
print('basic feasible solutions =')
print(T)
print('max f(x) =', max_value)

basic feasible solutions =
[[ 2.  4.  0.  0.]
 [ 2.  0.  3.  0.]
 [ 0.  4.  0. 12.]
 [ 0.  0.  1.  4.]]
max f(x) = 10.0


In [ ]:
Q = basic_solution(P,b_2)

number of basic solutions: 10


In [ ]:
basic_feasible_2, max_value_2 = find_maximum(Q,f_2)

In [ ]:
P = np.array([[6, 3, 1, 0, 0], [1, 1, 0, 1, 0], [2, 6, 0, 0, 1]])
b_2 = np.array([[96], [18], [72]])

In [ ]:
f_2 = np.array([80, 70, 0, 0, 0])

In [ ]:

print('basic feasible solutions =')
print(basic_feasible_2)
print('max 80x+70y =', max_value_2)